# Generated by Django 3.2.8 on 2021-10-26 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('firstName', models.CharField(max_length=200)),
                ('lastName', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=500)),
                ('username', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('userStatus', models.CharField(blank=True, default='Hey there, Im a new user', max_length=200, null=True)),
                ('profileImage', models.ImageField(blank=True, default='profiles/user-default.png', null=True, upload_to='profiles/')),
                ('socialTitle1', models.CharField(blank=True, max_length=200, null=True)),
                ('socialLink1', models.CharField(blank=True, max_length=200, null=True)),
                ('socialTitle2', models.CharField(blank=True, max_length=200, null=True)),
                ('socialLink2', models.CharField(blank=True, max_length=200, null=True)),
                ('socialTitle3', models.CharField(blank=True, max_length=200, null=True)),
                ('socialLink3', models.CharField(blank=True, max_length=200, null=True)),
                ('socialTitle4', models.CharField(blank=True, max_length=200, null=True)),
                ('socialLink4', models.CharField(blank=True, max_length=200, null=True)),
                ('socialTitle5', models.CharField(blank=True, max_length=200, null=True)),
                ('socialLink5', models.CharField(blank=True, max_length=200, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
