# Generated by Django 3.2.8 on 2021-10-28 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20211028_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='isAdmin',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='isDonator',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='isNewUser',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='isSuperDonator',
            field=models.BooleanField(),
        ),
    ]
