# Generated by Django 3.2.8 on 2021-10-28 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_isowner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='isAdmin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='isDonator',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='isOwner',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='isSuperDonator',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='userStatus',
            field=models.CharField(blank=True, default='New user', max_length=200, null=True),
        ),
    ]
